AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template to create IAM User

Parameters:
  UserName:
    Type: String
    Description: IAM User Name
    Default: Joe

Resources:
  AdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
  AdminGroup:
    Type: AWS::IAM::Group
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: "Because I want to!"
    Properties:
      GroupName: Admin
  Users:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref AdminGroup
      Users:
        - !Ref AdminUser
