---
name: CI/CD

on: [push]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: cfn-lint
        uses: scottbrenner/cfn-lint-action@master
        with:
          args: "cloudformation/*.yaml"
      - name: cfn_nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: "cloudformation/*.yaml"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: validate-template
        run: aws cloudformation validate-template --template-body foobar
